package com.fundpilot.backend.discipline.adapter.web.strategymanagement;
import com.fundpilot.backend.discipline.application.command.strategymanagement.DisciplineStrategyCommandHandler;
import com.fundpilot.backend.discipline.application.query.strategymanagement.DisciplineStrategyQueryHandler;
import com.fundpilot.backend.platform.web.RequestActorAttributes;
import java.math.BigDecimal; import java.util.List; import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/discipline/strategies") @RequiredArgsConstructor public class DisciplineStrategyController {
    private final DisciplineStrategyCommandHandler commands; private final DisciplineStrategyQueryHandler queries;
    @GetMapping("/funds/{legacyFundId}") public Response<List<View>> list(@RequestAttribute(RequestActorAttributes.USER_ID) Long ownerId, @PathVariable long legacyFundId) { return Response.ok(queries.listByLegacyFund(ownerId, legacyFundId).stream().map(View::from).toList()); }
    @GetMapping("/portfolio-funds/{portfolioFundId}") public Response<List<View>> listPortfolioFund(@RequestAttribute(RequestActorAttributes.USER_ID) Long ownerId, @PathVariable long portfolioFundId) { return Response.ok(queries.listByPortfolioFund(ownerId, portfolioFundId).stream().map(View::from).toList()); }
    @GetMapping("/funds/{legacyFundId}/active") public Response<View> active(@RequestAttribute(RequestActorAttributes.USER_ID) Long ownerId, @PathVariable long legacyFundId) { var value = queries.activeByLegacyFund(ownerId, legacyFundId); return Response.ok(value == null ? null : View.from(value)); }
    @GetMapping("/portfolio-funds/{portfolioFundId}/active") public Response<View> activePortfolioFund(@RequestAttribute(RequestActorAttributes.USER_ID) Long ownerId, @PathVariable long portfolioFundId) { var value = queries.activeByPortfolioFund(ownerId, portfolioFundId); return Response.ok(value == null ? null : View.from(value)); }
    @GetMapping("/funds/{legacyFundId}/recommendation") public Response<RecommendationView> recommendation(@RequestAttribute(RequestActorAttributes.USER_ID) Long ownerId, @PathVariable long legacyFundId) { var value = queries.recommendation(ownerId, legacyFundId); return Response.ok(new RecommendationView(value.category(), value.version(), value.profitActivationPercent(), value.stopLossPullbackPercent(), value.profitHarvestPercent(), value.minimumHoldingPercent(), value.maxSingleSellPercent(), value.cooldownTradingDays())); }
    @GetMapping("/portfolio-funds/{portfolioFundId}/recommendation") public Response<RecommendationView> portfolioFundRecommendation(@RequestAttribute(RequestActorAttributes.USER_ID) Long ownerId, @PathVariable long portfolioFundId) { var value = queries.recommendationByPortfolioFund(ownerId, portfolioFundId); return Response.ok(new RecommendationView(value.category(), value.version(), value.profitActivationPercent(), value.stopLossPullbackPercent(), value.profitHarvestPercent(), value.minimumHoldingPercent(), value.maxSingleSellPercent(), value.cooldownTradingDays())); }
    @PostMapping("/funds/{legacyFundId}") public Response<View> create(@RequestAttribute(RequestActorAttributes.USER_ID) Long ownerId, @PathVariable long legacyFundId, @RequestBody Request request) { return Response.ok(View.from(commands.create(ownerId, legacyFundId, request.toInput()))); }
    @PostMapping("/portfolio-funds/{portfolioFundId}") public Response<View> createPortfolioFund(@RequestAttribute(RequestActorAttributes.USER_ID) Long ownerId, @PathVariable long portfolioFundId, @RequestBody Request request) { return Response.ok(View.from(commands.createForPortfolioFund(ownerId, portfolioFundId, request.toInput()))); }
    @PutMapping("/{strategyId}") public Response<View> update(@RequestAttribute(RequestActorAttributes.USER_ID) Long ownerId, @PathVariable long strategyId, @RequestBody Request request) { return Response.ok(View.from(commands.update(ownerId, strategyId, request.toInput()))); }
    @PostMapping("/{strategyId}/{action:activate|retire}") public Response<View> action(@RequestAttribute(RequestActorAttributes.USER_ID) Long ownerId, @PathVariable long strategyId, @PathVariable String action) { return Response.ok(View.from("activate".equals(action) ? commands.activate(ownerId, strategyId) : commands.retire(ownerId, strategyId))); }
    public record Request(BigDecimal profitActivationPercent, BigDecimal stopLossPullbackPercent, BigDecimal profitHarvestPercent, BigDecimal minimumHoldingPercent, BigDecimal maxSingleSellPercent, Integer cooldownTradingDays, String presetFundCategory, Integer presetVersion, boolean customized) { DisciplineStrategyCommandHandler.Input toInput() { return new DisciplineStrategyCommandHandler.Input(profitActivationPercent, stopLossPullbackPercent, profitHarvestPercent, minimumHoldingPercent, maxSingleSellPercent, cooldownTradingDays, presetFundCategory, presetVersion, customized); } }
    public record View(Long id, long portfolioFundId, String status, BigDecimal profitActivationPercent, BigDecimal stopLossPullbackPercent, BigDecimal profitHarvestPercent, BigDecimal minimumHoldingPercent, BigDecimal maxSingleSellPercent, Integer cooldownTradingDays, String presetFundCategory, Integer presetVersion, boolean customized, String takeProfitPhase) { static View from(DisciplineStrategyCommandHandler.Result v) { return new View(v.id(), v.portfolioFundId(), v.status(), v.profitActivationPercent(), v.stopLossPullbackPercent(), v.profitHarvestPercent(), v.minimumHoldingPercent(), v.maxSingleSellPercent(), v.cooldownTradingDays(), v.presetFundCategory(), v.presetVersion(), v.customized(), v.takeProfitPhase()); } }
    public record RecommendationView(String fundCategory, int presetVersion, BigDecimal profitActivationPercent, BigDecimal stopLossPullbackPercent, BigDecimal profitHarvestPercent, BigDecimal minimumHoldingPercent, BigDecimal maxSingleSellPercent, int cooldownTradingDays) {}
    record Response<T>(boolean success, T data, String code, String message) { static <T> Response<T> ok(T data) { return new Response<>(true, data, null, null); } }
}
