-- =============================================================================
-- V1: 基金纪律策略初始 schema
-- 严格对齐 backend/src/main/java/com/fundpilot/backend 下 7 个 Entity 当前字段
-- 公共列(继承自 AbstractEntity):id / version / created_date / updated_date / deleted_date
-- 软删使用 @SoftDelete(strategy = TIMESTAMP),deleted_date IS NULL 即未删
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. fund —— 基金产品
-- -----------------------------------------------------------------------------
CREATE TABLE fund
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                 BIGINT,
    created_date            TIMESTAMPTZ,
    updated_date            TIMESTAMPTZ,
    deleted_date            TIMESTAMPTZ,

    fund_code               VARCHAR(255),
    fund_name               VARCHAR(255),
    investment_target       VARCHAR(32),
    operation_mode          VARCHAR(32),
    investment_philosophy   VARCHAR(32),
    fund_category           VARCHAR(32),
    status                  VARCHAR(32),
    planned_total_amount    NUMERIC(19, 8),
    peak_nav                NUMERIC(19, 8),
    holding_period_peak_nav NUMERIC(19, 8)
);

CREATE INDEX idx_fund_status ON fund (status) WHERE deleted_date IS NULL;

-- -----------------------------------------------------------------------------
-- 2. fund_nav_history —— 基金净值历史
-- -----------------------------------------------------------------------------
CREATE TABLE fund_nav_history
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         BIGINT,
    created_date    TIMESTAMPTZ,
    updated_date    TIMESTAMPTZ,
    deleted_date    TIMESTAMPTZ,

    fund_id         BIGINT,
    nav_date        TIMESTAMPTZ,
    accumulated_nav NUMERIC(19, 8),

    CONSTRAINT fk_fund_nav_history_fund FOREIGN KEY (fund_id) REFERENCES fund (id)
);

CREATE INDEX idx_fund_nav_history_fund_date ON fund_nav_history (fund_id, nav_date) WHERE deleted_date IS NULL;
-- (fund_id, nav_date 按日去重) 部分唯一索引:每只基金每个交易日最多一行净值
-- nav_date 是 timestamptz,直接 ::date 转换依赖会话时区,PG 视为非 IMMUTABLE 不能建表达式索引。
-- 先 AT TIME ZONE 'UTC' 固定到 UTC 时区再转 date,转换变为 IMMUTABLE。
CREATE UNIQUE INDEX uq_fund_nav_history_daily
    ON fund_nav_history (fund_id, ((nav_date AT TIME ZONE 'UTC')::date)) WHERE deleted_date IS NULL;

-- -----------------------------------------------------------------------------
-- 3. fund_strategy —— 策略参数 + 该版本运行时状态(原 user_fund_strategy)
-- -----------------------------------------------------------------------------
CREATE TABLE fund_strategy
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                    BIGINT,
    created_date               TIMESTAMPTZ,
    updated_date               TIMESTAMPTZ,
    deleted_date               TIMESTAMPTZ,

    fund_id                    BIGINT,
    status                     VARCHAR(32),
    tier1_drawdown             NUMERIC(19, 8),
    tier2_drawdown             NUMERIC(19, 8),
    tier3_drawdown             NUMERIC(19, 8),
    tier4_drawdown             NUMERIC(19, 8),
    tier1_ratio                NUMERIC(19, 8),
    tier2_ratio                NUMERIC(19, 8),
    tier3_ratio                NUMERIC(19, 8),
    tier4_ratio                NUMERIC(19, 8),
    weekly_cool_down_threshold NUMERIC(19, 8),
    stop_loss_pullback_percent NUMERIC(19, 8),
    tier1_added_at             TIMESTAMPTZ,
    tier2_added_at             TIMESTAMPTZ,
    tier3_added_at             TIMESTAMPTZ,
    tier4_added_at             TIMESTAMPTZ,

    CONSTRAINT fk_fund_strategy_fund FOREIGN KEY (fund_id) REFERENCES fund (id)
);

CREATE INDEX idx_fund_strategy_fund_status ON fund_strategy (fund_id, status) WHERE deleted_date IS NULL;
-- 同一基金最多 1 份 EFFECTIVE 参数(部分唯一索引兜底)
CREATE UNIQUE INDEX uq_fund_strategy_effective
    ON fund_strategy (fund_id) WHERE status = 'EFFECTIVE' AND deleted_date IS NULL;

-- -----------------------------------------------------------------------------
-- 4. fund_strategy_activation —— 基金策略激活记录(激活/退役谱系)
-- -----------------------------------------------------------------------------
CREATE TABLE fund_strategy_activation
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          BIGINT,
    created_date     TIMESTAMPTZ,
    updated_date     TIMESTAMPTZ,
    deleted_date     TIMESTAMPTZ,

    fund_id          BIGINT,
    fund_strategy_id BIGINT,
    activated_at     TIMESTAMPTZ,
    deactivated_at   TIMESTAMPTZ,

    CONSTRAINT fk_fsa_fund FOREIGN KEY (fund_id) REFERENCES fund (id),
    CONSTRAINT fk_fsa_fund_strategy FOREIGN KEY (fund_strategy_id) REFERENCES fund_strategy (id)
);

CREATE INDEX idx_fsa_fund_activated_at ON fund_strategy_activation (fund_id, activated_at) WHERE deleted_date IS NULL;

-- -----------------------------------------------------------------------------
-- 5. signal_log —— 每日信号快照
--    suggestedMeasure 为 @Embedded Measure -> 拆为 value + measure_unit 两列
--    signal_type 字段 entity 上无 @Enumerated -> 默认 ORDINAL -> SMALLINT
-- -----------------------------------------------------------------------------
CREATE TABLE signal_log
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                  BIGINT,
    created_date             TIMESTAMPTZ,
    updated_date             TIMESTAMPTZ,
    deleted_date             TIMESTAMPTZ,

    fund_id                  BIGINT,
    fund_strategy_id         BIGINT,
    signal_date              TIMESTAMPTZ,
    trigger_nav              NUMERIC(19, 8),
    trigger_tier             INTEGER,
    coefficient              NUMERIC(19, 8),
    signal_type              SMALLINT,
    value                    NUMERIC(19, 8),
    measure_unit             VARCHAR(32),
    reason                   TEXT,
    warnings                 TEXT,
    hard_constraint_breaches TEXT,

    CONSTRAINT fk_signal_log_fund FOREIGN KEY (fund_id) REFERENCES fund (id),
    CONSTRAINT fk_signal_log_fund_strategy FOREIGN KEY (fund_strategy_id) REFERENCES fund_strategy (id)
);

CREATE INDEX idx_signal_log_signal_date ON signal_log (signal_date) WHERE deleted_date IS NULL;
CREATE INDEX idx_signal_log_fund_signal_type ON signal_log (fund_id, signal_type) WHERE deleted_date IS NULL;
-- (fund_id, signal_date 按日去重) 部分唯一索引:每只基金每个交易日最多一行
-- 同 uq_fund_nav_history_daily,用 AT TIME ZONE 'UTC' 让转换 IMMUTABLE。
CREATE UNIQUE INDEX uq_signal_log_daily
    ON signal_log (fund_id, ((signal_date AT TIME ZONE 'UTC')::date)) WHERE deleted_date IS NULL;

-- -----------------------------------------------------------------------------
-- 6. fund_transaction —— 基金交易事件(原 fund_flow)
-- -----------------------------------------------------------------------------
CREATE TABLE fund_transaction
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                     BIGINT,
    created_date                TIMESTAMPTZ,
    updated_date                TIMESTAMPTZ,
    deleted_date                TIMESTAMPTZ,

    fund_id                     BIGINT NOT NULL,
    amount                      NUMERIC(19, 8),
    confirm_time                TIMESTAMPTZ,
    cancel_time                 TIMESTAMPTZ,
    status                      VARCHAR(32),
    source                      VARCHAR(32),
    shares                      NUMERIC(19, 8),
    nav                         NUMERIC(19, 8),
    signal_log_id               BIGINT,
    related_fund_transaction_id BIGINT,

    CONSTRAINT fk_ft_fund FOREIGN KEY (fund_id) REFERENCES fund (id),
    CONSTRAINT fk_ft_signal_log FOREIGN KEY (signal_log_id) REFERENCES signal_log (id),
    CONSTRAINT fk_ft_related FOREIGN KEY (related_fund_transaction_id) REFERENCES fund_transaction (id)
);

CREATE INDEX idx_ft_fund_confirm_time ON fund_transaction (fund_id, confirm_time) WHERE deleted_date IS NULL;
CREATE INDEX idx_ft_status_confirm ON fund_transaction (status, confirm_time) WHERE deleted_date IS NULL;
CREATE INDEX idx_ft_signal_log ON fund_transaction (signal_log_id) WHERE deleted_date IS NULL;

-- -----------------------------------------------------------------------------
-- 7. strategy_backtest —— 策略回测结果
-- -----------------------------------------------------------------------------
CREATE TABLE strategy_backtest
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                       BIGINT,
    created_date                  TIMESTAMPTZ,
    updated_date                  TIMESTAMPTZ,
    deleted_date                  TIMESTAMPTZ,

    fund_strategy_id              BIGINT,
    backtest_start_date           TIMESTAMPTZ,
    backtest_end_date             TIMESTAMPTZ,
    strategy_return               NUMERIC(19, 8),
    strategy_max_drawdown         NUMERIC(19, 8),
    benchmark_hs300_return        NUMERIC(19, 8),
    benchmark_all_in_return       NUMERIC(19, 8),
    benchmark_dca_return          NUMERIC(19, 8),
    benchmark_hs300_max_drawdown  NUMERIC(19, 8),
    benchmark_all_in_max_drawdown NUMERIC(19, 8),
    benchmark_dca_max_drawdown    NUMERIC(19, 8),
    passed                        BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_backtest_fund_strategy FOREIGN KEY (fund_strategy_id) REFERENCES fund_strategy (id)
);

CREATE INDEX idx_backtest_fund_strategy ON strategy_backtest (fund_strategy_id, passed) WHERE deleted_date IS NULL;
