CREATE TABLE portfolio_return_snapshot
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               BIGINT,
    created_date          TIMESTAMPTZ,
    updated_date          TIMESTAMPTZ,
    deleted_date          TIMESTAMPTZ,
    business_date         DATE NOT NULL,
    invested_amount       NUMERIC(19, 8) NOT NULL,
    redeemed_amount       NUMERIC(19, 8) NOT NULL,
    fee_amount            NUMERIC(19, 8) NOT NULL,
    holding_amount        NUMERIC(19, 8) NOT NULL,
    realized_pnl          NUMERIC(19, 8),
    unrealized_pnl        NUMERIC(19, 8),
    total_return          NUMERIC(19, 8) NOT NULL,
    valuation_complete    BOOLEAN NOT NULL,
    missing_fund_codes    VARCHAR(512),
    captured_at           TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uq_portfolio_return_snapshot_date
    ON portfolio_return_snapshot (business_date) WHERE deleted_date IS NULL;
