CREATE TABLE fund_group
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      BIGINT,
    created_date TIMESTAMPTZ,
    updated_date TIMESTAMPTZ,
    deleted_date TIMESTAMPTZ,
    name         VARCHAR(20) NOT NULL,
    sort_order   INTEGER NOT NULL
);

CREATE UNIQUE INDEX uq_fund_group_name
    ON fund_group (lower(name)) WHERE deleted_date IS NULL;

CREATE TABLE fund_group_member
(
    fund_id  BIGINT NOT NULL REFERENCES fund (id) ON DELETE CASCADE,
    group_id BIGINT NOT NULL REFERENCES fund_group (id) ON DELETE CASCADE,
    PRIMARY KEY (fund_id, group_id)
);

CREATE INDEX idx_fund_group_member_group ON fund_group_member (group_id);
