CREATE TABLE site_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    created_date TIMESTAMPTZ,
    updated_date TIMESTAMPTZ,
    deleted_date TIMESTAMPTZ,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(16) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_site_user_enabled ON site_user (enabled) WHERE deleted_date IS NULL;
