-- ProductCatalog expand migration. Legacy fund/fund_dict columns remain readable for rollback.
CREATE TABLE fund_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_date TIMESTAMPTZ,
    fund_code VARCHAR(16) NOT NULL,
    fund_name VARCHAR(255) NOT NULL,
    raw_name VARCHAR(64),
    product_type VARCHAR(32),
    investment_target VARCHAR(32),
    benchmark_index_code VARCHAR(64),
    default_discipline_category VARCHAR(32)
);

CREATE UNIQUE INDEX uq_fund_product_code
    ON fund_product (fund_code) WHERE deleted_date IS NULL;
CREATE INDEX idx_fund_product_name
    ON fund_product (fund_name) WHERE deleted_date IS NULL;

-- Conflicts are retained for explicit reconciliation instead of silently discarding
-- differences between the global dictionary and per-user legacy fund rows.
CREATE TABLE fund_product_migration_conflict (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_code VARCHAR(16) NOT NULL,
    field_name VARCHAR(64) NOT NULL,
    candidate_values TEXT NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    resolution_note TEXT,
    CONSTRAINT uq_fund_product_migration_conflict UNIQUE (fund_code, field_name)
);

WITH candidates AS (
    SELECT fund_code, 'fund_name' AS field_name, fund_name AS field_value
    FROM fund_dict WHERE deleted_date IS NULL
    UNION ALL
    SELECT fund_code, 'fund_name', fund_name FROM fund
    UNION ALL
    SELECT fund_code, 'product_type', fund_sub_type FROM fund_dict WHERE deleted_date IS NULL
    UNION ALL
    SELECT fund_code, 'product_type', fund_sub_type FROM fund
    UNION ALL
    SELECT fund_code, 'investment_target', investment_target FROM fund
    UNION ALL
    SELECT fund_code, 'benchmark_index_code', benchmark_index_code
    FROM fund_dict WHERE deleted_date IS NULL
    UNION ALL
    SELECT fund_code, 'benchmark_index_code', benchmark_index_code FROM fund
    UNION ALL
    SELECT fund_code, 'default_discipline_category', fund_category
    FROM fund_dict WHERE deleted_date IS NULL
    UNION ALL
    SELECT fund_code, 'default_discipline_category', fund_category FROM fund
), normalized AS (
    SELECT trim(fund_code) AS fund_code, field_name, trim(field_value) AS field_value
    FROM candidates
    WHERE fund_code IS NOT NULL AND trim(fund_code) <> ''
      AND field_value IS NOT NULL AND trim(field_value) <> ''
)
INSERT INTO fund_product_migration_conflict (fund_code, field_name, candidate_values)
SELECT fund_code, field_name, string_agg(DISTINCT field_value, ' | ' ORDER BY field_value)
FROM normalized
GROUP BY fund_code, field_name
HAVING count(DISTINCT field_value) > 1;

WITH dictionary_latest AS (
    SELECT DISTINCT ON (trim(fund_code))
           trim(fund_code) AS fund_code, fund_name, raw_name, fund_sub_type,
           fund_category
    FROM fund_dict
    WHERE deleted_date IS NULL AND fund_code IS NOT NULL AND trim(fund_code) <> ''
    ORDER BY trim(fund_code), updated_date DESC NULLS LAST, id DESC
), dictionary_benchmark AS (
    SELECT DISTINCT ON (trim(fund_code))
           trim(fund_code) AS fund_code, benchmark_index_code
    FROM fund_dict
    WHERE deleted_date IS NULL AND fund_code IS NOT NULL AND trim(fund_code) <> ''
      AND benchmark_index_code IS NOT NULL AND trim(benchmark_index_code) <> ''
    ORDER BY trim(fund_code), updated_date DESC NULLS LAST, id DESC
), fund_latest AS (
    SELECT DISTINCT ON (trim(fund_code))
           trim(fund_code) AS fund_code, fund_name, fund_sub_type, investment_target,
           benchmark_index_code, fund_category
    FROM fund
    WHERE fund_code IS NOT NULL AND trim(fund_code) <> ''
    ORDER BY trim(fund_code), (deleted_date IS NULL) DESC, updated_date DESC NULLS LAST, id DESC
), fund_benchmark AS (
    SELECT DISTINCT ON (trim(fund_code))
           trim(fund_code) AS fund_code, benchmark_index_code
    FROM fund
    WHERE fund_code IS NOT NULL AND trim(fund_code) <> ''
      AND benchmark_index_code IS NOT NULL AND trim(benchmark_index_code) <> ''
    ORDER BY trim(fund_code), (deleted_date IS NULL) DESC, updated_date DESC NULLS LAST, id DESC
), codes AS (
    SELECT fund_code FROM dictionary_latest
    UNION
    SELECT fund_code FROM fund_latest
), selected AS (
    SELECT c.fund_code,
           COALESCE(d.fund_name, f.fund_name, c.fund_code) AS fund_name,
           d.raw_name,
           COALESCE(d.fund_sub_type, f.fund_sub_type) AS product_type,
           f.investment_target,
           COALESCE(db.benchmark_index_code, fb.benchmark_index_code) AS benchmark_index_code,
           COALESCE(d.fund_category, f.fund_category) AS default_discipline_category
    FROM codes c
    LEFT JOIN dictionary_latest d ON d.fund_code = c.fund_code
    LEFT JOIN dictionary_benchmark db ON db.fund_code = c.fund_code
    LEFT JOIN fund_latest f ON f.fund_code = c.fund_code
    LEFT JOIN fund_benchmark fb ON fb.fund_code = c.fund_code
)
INSERT INTO fund_product (
    fund_code, fund_name, raw_name, product_type, investment_target,
    benchmark_index_code, default_discipline_category)
SELECT fund_code, fund_name, raw_name, product_type, investment_target,
       benchmark_index_code, default_discipline_category
FROM selected;

ALTER TABLE fund ADD COLUMN product_id BIGINT;
UPDATE fund f
SET product_id = p.id
FROM fund_product p
WHERE p.deleted_date IS NULL AND trim(f.fund_code) = p.fund_code;

ALTER TABLE fund ADD CONSTRAINT fk_fund_product
    FOREIGN KEY (product_id) REFERENCES fund_product (id);
CREATE INDEX idx_fund_product_id ON fund (product_id) WHERE deleted_date IS NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM fund
        WHERE fund_code IS NOT NULL AND trim(fund_code) <> '' AND product_id IS NULL
    ) THEN
        RAISE EXCEPTION 'fund_product backfill left fund rows without product_id';
    END IF;
END $$;
