-- Portfolio expand migration. Legacy fund rows and memberships remain for rollback.
DO $$
DECLARE
    missing_owner_count BIGINT;
    missing_product_count BIGINT;
    duplicate_tracked_count BIGINT;
BEGIN
    SELECT count(*) INTO missing_owner_count FROM fund WHERE owner_id IS NULL;
    SELECT count(*) INTO missing_product_count FROM fund WHERE product_id IS NULL;
    SELECT count(*) INTO duplicate_tracked_count
    FROM (
        SELECT owner_id, product_id
        FROM fund
        WHERE deleted_date IS NULL AND owner_id IS NOT NULL AND product_id IS NOT NULL
        GROUP BY owner_id, product_id
        HAVING count(*) > 1
    ) duplicates;
    IF missing_owner_count > 0 OR missing_product_count > 0 OR duplicate_tracked_count > 0 THEN
        RAISE EXCEPTION
            'portfolio_fund backfill blocked: missing owner_id=%, missing product_id=%, duplicate tracked owner/product=%',
            missing_owner_count, missing_product_count, duplicate_tracked_count;
    END IF;
END $$;

CREATE TABLE portfolio_fund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    owner_id BIGINT NOT NULL,
    fund_product_id BIGINT NOT NULL,
    legacy_fund_id BIGINT,
    validity VARCHAR(16) NOT NULL,
    position_warning_enabled BOOLEAN NOT NULL,
    position_warning_ratio NUMERIC(19, 8) NOT NULL,
    voided_at TIMESTAMPTZ,
    voided_by BIGINT,
    void_reason TEXT,
    CONSTRAINT fk_portfolio_fund_owner FOREIGN KEY (owner_id) REFERENCES site_user (id),
    CONSTRAINT fk_portfolio_fund_product FOREIGN KEY (fund_product_id) REFERENCES fund_product (id),
    CONSTRAINT fk_portfolio_fund_legacy_fund FOREIGN KEY (legacy_fund_id) REFERENCES fund (id),
    CONSTRAINT fk_portfolio_fund_voided_by FOREIGN KEY (voided_by) REFERENCES site_user (id),
    CONSTRAINT uq_portfolio_fund_legacy_fund UNIQUE (legacy_fund_id),
    CONSTRAINT ck_portfolio_fund_validity CHECK (validity IN ('TRACKED', 'VOIDED')),
    CONSTRAINT ck_portfolio_fund_warning_ratio
        CHECK (position_warning_ratio > 0 AND position_warning_ratio <= 1),
    CONSTRAINT ck_portfolio_fund_void_audit CHECK (
        (validity = 'TRACKED' AND voided_at IS NULL AND voided_by IS NULL AND void_reason IS NULL)
        OR
        (validity = 'VOIDED' AND voided_at IS NOT NULL AND voided_by IS NOT NULL
            AND void_reason IS NOT NULL AND length(trim(void_reason)) > 0)
    )
);

CREATE UNIQUE INDEX uq_portfolio_fund_owner_product_tracked
    ON portfolio_fund (owner_id, fund_product_id) WHERE validity = 'TRACKED';
CREATE INDEX idx_portfolio_fund_owner_validity
    ON portfolio_fund (owner_id, validity);
CREATE INDEX idx_portfolio_fund_product
    ON portfolio_fund (fund_product_id);

INSERT INTO portfolio_fund (
    version, created_date, updated_date, owner_id, fund_product_id, legacy_fund_id,
    validity, position_warning_enabled, position_warning_ratio,
    voided_at, voided_by, void_reason
)
SELECT COALESCE(f.version, 0),
       COALESCE(f.created_date, now()),
       COALESCE(f.updated_date, f.created_date, now()),
       f.owner_id,
       f.product_id,
       f.id,
       CASE WHEN f.deleted_date IS NULL THEN 'TRACKED' ELSE 'VOIDED' END,
       f.position_warning_enabled,
       f.position_warning_ratio,
       f.deleted_date,
       CASE WHEN f.deleted_date IS NULL THEN NULL ELSE f.owner_id END,
       CASE WHEN f.deleted_date IS NULL THEN NULL ELSE 'LEGACY_ARCHIVED' END
FROM fund f;

CREATE TABLE portfolio_fund_group_member (
    portfolio_fund_id BIGINT NOT NULL REFERENCES portfolio_fund (id) ON DELETE CASCADE,
    group_id BIGINT NOT NULL REFERENCES fund_group (id) ON DELETE CASCADE,
    PRIMARY KEY (portfolio_fund_id, group_id)
);

CREATE INDEX idx_portfolio_fund_group_member_group
    ON portfolio_fund_group_member (group_id);

INSERT INTO portfolio_fund_group_member (portfolio_fund_id, group_id)
SELECT pf.id, fgm.group_id
FROM fund_group_member fgm
JOIN portfolio_fund pf ON pf.legacy_fund_id = fgm.fund_id;

DO $$
BEGIN
    IF (SELECT count(*) FROM portfolio_fund) <> (SELECT count(*) FROM fund) THEN
        RAISE EXCEPTION 'portfolio_fund backfill row count mismatch';
    END IF;
    IF EXISTS (
        SELECT 1
        FROM fund f
        JOIN portfolio_fund pf ON pf.legacy_fund_id = f.id
        WHERE pf.owner_id <> f.owner_id
           OR pf.fund_product_id <> f.product_id
           OR (f.deleted_date IS NULL AND pf.validity <> 'TRACKED')
           OR (f.deleted_date IS NOT NULL AND pf.validity <> 'VOIDED')
    ) THEN
        RAISE EXCEPTION 'portfolio_fund backfill reconciliation mismatch';
    END IF;
    IF (SELECT count(*) FROM portfolio_fund_group_member)
            <> (SELECT count(*) FROM fund_group_member) THEN
        RAISE EXCEPTION 'portfolio_fund group membership backfill row count mismatch';
    END IF;
END $$;
