-- MarketData expand migration. Legacy fund references and user_config.watched_indices
-- remain readable until the contract migration.
ALTER TABLE fund_nav_history ADD COLUMN fund_product_id BIGINT;

UPDATE fund_nav_history n
SET fund_product_id = p.id
FROM fund_product p
WHERE p.deleted_date IS NULL
  AND trim(n.fund_code) = p.fund_code;

ALTER TABLE fund_nav_history ADD CONSTRAINT fk_fund_nav_history_product
    FOREIGN KEY (fund_product_id) REFERENCES fund_product (id);
CREATE INDEX idx_fund_nav_history_product_date
    ON fund_nav_history (fund_product_id, nav_date)
    WHERE deleted_date IS NULL;
CREATE UNIQUE INDEX uq_fund_nav_history_product_daily
    ON fund_nav_history (fund_product_id, ((nav_date AT TIME ZONE 'UTC')::date))
    WHERE deleted_date IS NULL;

ALTER TABLE market_indicator_snapshot ADD COLUMN fund_product_id BIGINT;

UPDATE market_indicator_snapshot s
SET fund_product_id = p.id
FROM fund_product p
WHERE p.deleted_date IS NULL
  AND trim(s.fund_code) = p.fund_code;

ALTER TABLE market_indicator_snapshot ADD CONSTRAINT fk_market_indicator_snapshot_product
    FOREIGN KEY (fund_product_id) REFERENCES fund_product (id);
CREATE INDEX idx_market_indicator_snapshot_product_date
    ON market_indicator_snapshot (fund_product_id, snapshot_date)
    WHERE deleted_date IS NULL;
CREATE UNIQUE INDEX uq_market_indicator_snapshot_product_daily
    ON market_indicator_snapshot (fund_product_id, snapshot_date)
    WHERE deleted_date IS NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM user_config
        WHERE deleted_date IS NULL AND owner_id IS NULL
    ) THEN
        RAISE EXCEPTION 'active user_config rows remain without owner_id';
    END IF;

    IF EXISTS (
        SELECT owner_id
        FROM user_config
        WHERE deleted_date IS NULL
        GROUP BY owner_id
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'multiple active user_config rows exist for one owner';
    END IF;
END $$;

DROP INDEX uq_user_config_singleton;
CREATE UNIQUE INDEX uq_user_config_owner
    ON user_config (owner_id)
    WHERE deleted_date IS NULL;

CREATE TABLE market_watched_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_date TIMESTAMPTZ,
    owner_id BIGINT NOT NULL,
    index_code VARCHAR(64) NOT NULL,
    display_order INTEGER NOT NULL,
    CONSTRAINT fk_market_watched_index_owner
        FOREIGN KEY (owner_id) REFERENCES site_user (id),
    CONSTRAINT ck_market_watched_index_code_not_blank
        CHECK (trim(index_code) <> ''),
    CONSTRAINT ck_market_watched_index_display_order
        CHECK (display_order >= 0)
);

CREATE UNIQUE INDEX uq_market_watched_index_owner_code
    ON market_watched_index (owner_id, index_code)
    WHERE deleted_date IS NULL;
CREATE INDEX idx_market_watched_index_owner_order
    ON market_watched_index (owner_id, display_order)
    WHERE deleted_date IS NULL;

WITH parsed AS (
    SELECT c.owner_id,
           trim(entry.index_code) AS index_code,
           entry.ordinality - 1 AS display_order
    FROM user_config c
    CROSS JOIN LATERAL regexp_split_to_table(c.watched_indices, ',')
        WITH ORDINALITY AS entry(index_code, ordinality)
    WHERE c.deleted_date IS NULL
      AND c.watched_indices IS NOT NULL
      AND trim(entry.index_code) <> ''
), deduplicated AS (
    SELECT owner_id, index_code, min(display_order) AS display_order
    FROM parsed
    GROUP BY owner_id, index_code
)
INSERT INTO market_watched_index (owner_id, index_code, display_order)
SELECT owner_id, index_code, display_order
FROM deduplicated
ORDER BY owner_id, display_order;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM fund_nav_history
        WHERE deleted_date IS NULL AND fund_product_id IS NULL
    ) THEN
        RAISE EXCEPTION 'active fund_nav_history rows remain without fund_product_id';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM market_indicator_snapshot
        WHERE deleted_date IS NULL AND fund_product_id IS NULL
    ) THEN
        RAISE EXCEPTION 'active market_indicator_snapshot rows remain without fund_product_id';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM user_config
        WHERE deleted_date IS NULL
          AND watched_indices IS NOT NULL
          AND trim(watched_indices) <> ''
          AND owner_id IS NULL
    ) THEN
        RAISE EXCEPTION 'active watched index configuration remains without owner_id';
    END IF;

    IF (
        SELECT count(*)
        FROM market_watched_index
        WHERE deleted_date IS NULL
    ) <> (
        SELECT count(*)
        FROM (
            SELECT DISTINCT c.owner_id, trim(entry.index_code) AS index_code
            FROM user_config c
            CROSS JOIN LATERAL regexp_split_to_table(c.watched_indices, ',')
                AS entry(index_code)
            WHERE c.deleted_date IS NULL
              AND c.watched_indices IS NOT NULL
              AND trim(entry.index_code) <> ''
        ) expected
    ) THEN
        RAISE EXCEPTION 'market watched index backfill count mismatch';
    END IF;
END $$;
