-- =============================================================================
-- V3: 本期新增三张表(issue #3)
--   1. user_config               — 单用户账户配置,存 total_investable_capital
--                                   (总仓位 80% 硬约束分母,见 CONTEXT.md「总可投资金」)
--   2. trading_calendar          — A 股交易日历,MIN_HOLD_DAYS 5 个交易日判定要用(本期人工维护)
--   3. market_indicator_snapshot — 每日 14:50 行情指标快照(表级缓存):
--                                   MarketDataFetchJob 写,SignalGenerationJob 读,不再发外部请求
-- 三张表均继承 AbstractEntity 公共列(id/version/created_date/updated_date/deleted_date),
-- 软删遵循 ADR-0004(@SQLRestriction + @SQLDelete,deleted_date IS NULL 即未删)。
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. user_config —— 单用户账户配置(本期不存 userId,一行配置)
-- -----------------------------------------------------------------------------
CREATE TABLE user_config
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                  BIGINT,
    created_date             TIMESTAMPTZ,
    updated_date             TIMESTAMPTZ,
    deleted_date             TIMESTAMPTZ,

    total_investable_capital NUMERIC(19, 8) NOT NULL
);

-- -----------------------------------------------------------------------------
-- 2. trading_calendar —— A 股交易日历(本期人工维护,不做自动同步)
--    MIN_HOLD_DAYS 5 个交易日判定要查这张表;calendar_date 全局唯一。
-- -----------------------------------------------------------------------------
CREATE TABLE trading_calendar
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT,
    created_date  TIMESTAMPTZ,
    updated_date  TIMESTAMPTZ,
    deleted_date  TIMESTAMPTZ,

    calendar_date DATE      NOT NULL,
    is_trading_day BOOLEAN   NOT NULL
);

CREATE UNIQUE INDEX uq_trading_calendar_date
    ON trading_calendar (calendar_date) WHERE deleted_date IS NULL;

-- -----------------------------------------------------------------------------
-- 3. market_indicator_snapshot —— 每日 14:50 行情指标快照(表级缓存)
--    每只基金每日一行;MarketDataFetchJob 写,SignalGenerationJob 读,不再发外部请求。
--    weekly_macd_state / volume_state 见对应枚举(WeeklyMacdState / VolumeState)。
-- -----------------------------------------------------------------------------
CREATE TABLE market_indicator_snapshot
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                BIGINT,
    created_date           TIMESTAMPTZ,
    updated_date           TIMESTAMPTZ,
    deleted_date           TIMESTAMPTZ,

    fund_id                BIGINT      NOT NULL,
    snapshot_date          DATE        NOT NULL,
    current_nav            NUMERIC(19, 8),
    price_above_year_line  BOOLEAN,
    year_line_rising       BOOLEAN,
    weekly_macd_state      VARCHAR(32),
    volume_state           VARCHAR(32),
    weekly_drop_percent    NUMERIC(19, 8),
    is_sixty_day_high      BOOLEAN,

    CONSTRAINT fk_mis_fund FOREIGN KEY (fund_id) REFERENCES fund (id)
);

CREATE INDEX idx_mis_fund_snapshot_date
    ON market_indicator_snapshot (fund_id, snapshot_date) WHERE deleted_date IS NULL;

-- 每只基金每日只允许一行快照(部分唯一索引兜底,软删行不占唯一名额)
CREATE UNIQUE INDEX uq_mis_fund_snapshot_date
    ON market_indicator_snapshot (fund_id, snapshot_date) WHERE deleted_date IS NULL;
