-- Accounting expand migration.
-- Adds portfolio_fund_id to the ledger tables and moves position facts out of `fund`.
-- Legacy fund_transaction.fund_id, fund_lot.fund_id and fund.opened_at/cost_per_share/status
-- stay in place read-only so the previous application version can still be rolled back to.

DO $$
DECLARE
    orphan_transaction_count BIGINT;
    orphan_lot_count BIGINT;
BEGIN
    SELECT count(*) INTO orphan_transaction_count
    FROM fund_transaction t
    LEFT JOIN portfolio_fund pf ON pf.legacy_fund_id = t.fund_id
    WHERE pf.id IS NULL
      AND NOT EXISTS (
          SELECT 1 FROM fund f
          WHERE f.id = t.fund_id AND f.owner_id IS NULL AND f.deleted_date IS NOT NULL
      );

    SELECT count(*) INTO orphan_lot_count
    FROM fund_lot l
    LEFT JOIN portfolio_fund pf ON pf.legacy_fund_id = l.fund_id
    WHERE pf.id IS NULL
      AND NOT EXISTS (
          SELECT 1 FROM fund f
          WHERE f.id = l.fund_id AND f.owner_id IS NULL AND f.deleted_date IS NOT NULL
      );

    IF orphan_transaction_count > 0 OR orphan_lot_count > 0 THEN
        RAISE EXCEPTION
            'accounting backfill blocked: transactions without portfolio_fund=%, lots without portfolio_fund=%',
            orphan_transaction_count, orphan_lot_count;
    END IF;
END $$;

ALTER TABLE fund_transaction ADD COLUMN portfolio_fund_id BIGINT;
ALTER TABLE fund_lot ADD COLUMN portfolio_fund_id BIGINT;

UPDATE fund_transaction t
SET portfolio_fund_id = pf.id
FROM portfolio_fund pf
WHERE pf.legacy_fund_id = t.fund_id;

UPDATE fund_lot l
SET portfolio_fund_id = pf.id
FROM portfolio_fund pf
WHERE pf.legacy_fund_id = l.fund_id;

-- Deliberately left nullable: tightening to NOT NULL belongs with the code cutover that
-- writes portfolio_fund_id, so the currently deployed version keeps inserting successfully.
ALTER TABLE fund_transaction ADD CONSTRAINT fk_fund_transaction_portfolio_fund
    FOREIGN KEY (portfolio_fund_id) REFERENCES portfolio_fund (id);
ALTER TABLE fund_lot ADD CONSTRAINT fk_fund_lot_portfolio_fund
    FOREIGN KEY (portfolio_fund_id) REFERENCES portfolio_fund (id);

CREATE INDEX idx_fund_transaction_portfolio_fund_status
    ON fund_transaction (portfolio_fund_id, status);
CREATE INDEX idx_fund_lot_portfolio_fund
    ON fund_lot (portfolio_fund_id);

-- Position is the Accounting projection of the ledger. opened_at / cost_per_share / status
-- move here from `fund`; the ledger stays the source of truth and can always replay them.
CREATE TABLE accounting_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_date TIMESTAMPTZ,
    portfolio_fund_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    opened_at TIMESTAMPTZ,
    cost_per_share NUMERIC(19, 8),
    CONSTRAINT fk_accounting_position_portfolio_fund
        FOREIGN KEY (portfolio_fund_id) REFERENCES portfolio_fund (id),
    CONSTRAINT fk_accounting_position_owner FOREIGN KEY (owner_id) REFERENCES site_user (id),
    CONSTRAINT uq_accounting_position_portfolio_fund UNIQUE (portfolio_fund_id),
    CONSTRAINT ck_accounting_position_status CHECK (status IN ('EMPTY', 'OPEN', 'CLEARED')),
    CONSTRAINT ck_accounting_position_cost_per_share
        CHECK (cost_per_share IS NULL OR cost_per_share >= 0)
);

CREATE INDEX idx_accounting_position_owner_status ON accounting_position (owner_id, status);

INSERT INTO accounting_position (
    version, created_date, updated_date, portfolio_fund_id, owner_id,
    status, opened_at, cost_per_share
)
SELECT 0,
       COALESCE(f.created_date, now()),
       COALESCE(f.updated_date, f.created_date, now()),
       pf.id,
       pf.owner_id,
       CASE f.status
           WHEN 'HOLDING' THEN 'OPEN'
           WHEN 'CLEARED' THEN 'CLEARED'
           ELSE 'EMPTY'
       END,
       f.opened_at,
       f.cost_per_share
FROM portfolio_fund pf
JOIN fund f ON f.id = pf.legacy_fund_id;

DO $$
DECLARE
    ledger_mismatch BIGINT;
    position_mismatch BIGINT;
BEGIN
    IF (SELECT count(*) FROM accounting_position)
            <> (SELECT count(*) FROM portfolio_fund WHERE legacy_fund_id IS NOT NULL) THEN
        RAISE EXCEPTION 'accounting_position backfill row count mismatch';
    END IF;

    SELECT count(*) INTO ledger_mismatch
    FROM fund_transaction t
    JOIN portfolio_fund pf ON pf.id = t.portfolio_fund_id
    WHERE pf.legacy_fund_id <> t.fund_id;
    IF ledger_mismatch > 0 THEN
        RAISE EXCEPTION 'fund_transaction portfolio_fund backfill mismatch=%', ledger_mismatch;
    END IF;

    SELECT count(*) INTO ledger_mismatch
    FROM fund_lot l
    JOIN portfolio_fund pf ON pf.id = l.portfolio_fund_id
    WHERE pf.legacy_fund_id <> l.fund_id;
    IF ledger_mismatch > 0 THEN
        RAISE EXCEPTION 'fund_lot portfolio_fund backfill mismatch=%', ledger_mismatch;
    END IF;

    SELECT count(*) INTO position_mismatch
    FROM accounting_position p
    JOIN portfolio_fund pf ON pf.id = p.portfolio_fund_id
    JOIN fund f ON f.id = pf.legacy_fund_id
    WHERE p.owner_id <> pf.owner_id
       OR p.opened_at IS DISTINCT FROM f.opened_at
       OR p.cost_per_share IS DISTINCT FROM f.cost_per_share
       OR p.status <> CASE f.status
              WHEN 'HOLDING' THEN 'OPEN'
              WHEN 'CLEARED' THEN 'CLEARED'
              ELSE 'EMPTY'
          END;
    IF position_mismatch > 0 THEN
        RAISE EXCEPTION 'accounting_position backfill reconciliation mismatch=%', position_mismatch;
    END IF;
END $$;
