-- Discipline expand migration.
-- Keeps fund_strategy and signal_log intact while copying their owned facts to PortfolioFund-scoped tables.

DO $$
DECLARE
    orphan_strategy_count BIGINT;
    orphan_advice_count BIGINT;
    invalid_advice_type_count BIGINT;
BEGIN
    SELECT count(*) INTO orphan_strategy_count
    FROM fund_strategy strategy
    LEFT JOIN portfolio_fund portfolio_fund ON portfolio_fund.legacy_fund_id = strategy.fund_id
    WHERE strategy.fund_id IS NOT NULL AND portfolio_fund.id IS NULL;

    SELECT count(*) INTO orphan_advice_count
    FROM signal_log advice
    LEFT JOIN portfolio_fund portfolio_fund ON portfolio_fund.legacy_fund_id = advice.fund_id
    WHERE advice.fund_id IS NOT NULL AND portfolio_fund.id IS NULL;

    SELECT count(*) INTO invalid_advice_type_count
    FROM signal_log
    WHERE signal_type IS NOT NULL AND signal_type NOT IN ('NONE', 'BUILD', 'ADD', 'SELL');

    IF orphan_strategy_count > 0 OR orphan_advice_count > 0 OR invalid_advice_type_count > 0 THEN
        RAISE EXCEPTION 'discipline backfill blocked: strategies without portfolio_fund=%, advice without portfolio_fund=%, invalid advice types=%',
                orphan_strategy_count, orphan_advice_count, invalid_advice_type_count;
    END IF;
END $$;

CREATE TABLE discipline_strategy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_date TIMESTAMPTZ,
    legacy_strategy_id BIGINT UNIQUE,
    portfolio_fund_id BIGINT NOT NULL REFERENCES portfolio_fund (id),
    owner_id BIGINT NOT NULL REFERENCES site_user (id),
    status VARCHAR(32),
    stop_loss_pullback_percent NUMERIC(19, 8),
    profit_activation_percent NUMERIC(19, 8),
    profit_harvest_percent NUMERIC(19, 8),
    minimum_holding_percent NUMERIC(19, 8),
    max_single_sell_percent NUMERIC(19, 8),
    cooldown_trading_days INTEGER,
    preset_fund_category VARCHAR(32),
    preset_version INTEGER,
    customized BOOLEAN NOT NULL DEFAULT FALSE,
    take_profit_phase VARCHAR(32),
    cycle_started_at TIMESTAMPTZ,
    cycle_peak_nav NUMERIC(19, 8),
    triggered_advice_id BIGINT,
    cooldown_started_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_discipline_strategy_effective
    ON discipline_strategy (portfolio_fund_id) WHERE status = 'EFFECTIVE' AND deleted_date IS NULL;
CREATE INDEX idx_discipline_strategy_portfolio_fund ON discipline_strategy (portfolio_fund_id, status)
    WHERE deleted_date IS NULL;

INSERT INTO discipline_strategy (
    version, created_date, updated_date, deleted_date, legacy_strategy_id, portfolio_fund_id, owner_id,
    status, stop_loss_pullback_percent, profit_activation_percent, profit_harvest_percent,
    minimum_holding_percent, max_single_sell_percent, cooldown_trading_days, preset_fund_category,
    preset_version, customized, take_profit_phase, cycle_started_at, cycle_peak_nav, triggered_advice_id,
    cooldown_started_at
)
SELECT COALESCE(strategy.version, 0), COALESCE(strategy.created_date, now()),
       COALESCE(strategy.updated_date, strategy.created_date, now()), strategy.deleted_date, strategy.id,
       portfolio_fund.id, portfolio_fund.owner_id, strategy.status, strategy.stop_loss_pullback_percent,
       strategy.profit_activation_percent, strategy.profit_harvest_percent, strategy.minimum_holding_percent,
       strategy.max_single_sell_percent, strategy.cooldown_trading_days, strategy.preset_fund_category,
       strategy.preset_version, COALESCE(strategy.customized, FALSE), strategy.take_profit_phase,
       strategy.cycle_started_at, strategy.cycle_peak_nav, strategy.triggered_signal_id,
       strategy.cooldown_started_at
FROM fund_strategy strategy
JOIN portfolio_fund portfolio_fund ON portfolio_fund.legacy_fund_id = strategy.fund_id;

CREATE TABLE discipline_advice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_date TIMESTAMPTZ,
    legacy_signal_id BIGINT UNIQUE,
    portfolio_fund_id BIGINT NOT NULL REFERENCES portfolio_fund (id),
    owner_id BIGINT NOT NULL REFERENCES site_user (id),
    discipline_strategy_id BIGINT REFERENCES discipline_strategy (id),
    signal_date TIMESTAMPTZ,
    trigger_nav NUMERIC(19, 8),
    trigger_tier INTEGER,
    coefficient NUMERIC(19, 8),
    signal_type SMALLINT,
    suggested_value NUMERIC(19, 8),
    suggested_measure_unit VARCHAR(32),
    reason TEXT,
    warnings TEXT,
    hard_constraint_breaches TEXT,
    ignored_date TIMESTAMPTZ,
    response_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT ck_discipline_advice_response_status
        CHECK (response_status IN ('PENDING', 'RESPONDED', 'IGNORED'))
);

CREATE INDEX idx_discipline_advice_portfolio_fund_date
    ON discipline_advice (portfolio_fund_id, signal_date) WHERE deleted_date IS NULL;
CREATE UNIQUE INDEX uq_discipline_advice_daily
    ON discipline_advice (portfolio_fund_id, ((signal_date AT TIME ZONE 'UTC')::date))
    WHERE deleted_date IS NULL;

INSERT INTO discipline_advice (
    version, created_date, updated_date, deleted_date, legacy_signal_id, portfolio_fund_id, owner_id,
    discipline_strategy_id, signal_date, trigger_nav, trigger_tier, coefficient, signal_type,
    suggested_value, suggested_measure_unit, reason, warnings, hard_constraint_breaches, ignored_date
)
SELECT COALESCE(advice.version, 0), COALESCE(advice.created_date, now()),
       COALESCE(advice.updated_date, advice.created_date, now()), advice.deleted_date, advice.id,
       portfolio_fund.id, portfolio_fund.owner_id, discipline_strategy.id, advice.signal_date,
       advice.trigger_nav, advice.trigger_tier, advice.coefficient,
       CASE advice.signal_type
           WHEN 'NONE' THEN 0
           WHEN 'BUILD' THEN 1
           WHEN 'ADD' THEN 2
           WHEN 'SELL' THEN 3
       END,
       advice.value,
       advice.measure_unit, advice.reason, advice.warnings, advice.hard_constraint_breaches, advice.ignored_date
FROM signal_log advice
JOIN portfolio_fund portfolio_fund ON portfolio_fund.legacy_fund_id = advice.fund_id
LEFT JOIN discipline_strategy discipline_strategy
    ON discipline_strategy.legacy_strategy_id = advice.fund_strategy_id;

UPDATE discipline_advice
SET response_status = 'IGNORED'
WHERE ignored_date IS NOT NULL;

-- Accounting owns transaction execution, so the new advice key is stored independently of the
-- legacy signal FK. The old column remains for rollback/read comparison.
ALTER TABLE fund_transaction ADD COLUMN discipline_advice_id BIGINT;
ALTER TABLE fund_transaction ADD CONSTRAINT fk_fund_transaction_discipline_advice
    FOREIGN KEY (discipline_advice_id) REFERENCES discipline_advice (id);
UPDATE fund_transaction ft
SET discipline_advice_id = advice.id
FROM discipline_advice advice
WHERE advice.legacy_signal_id = ft.signal_log_id;
CREATE UNIQUE INDEX uq_fund_transaction_discipline_advice
    ON fund_transaction (discipline_advice_id)
    WHERE discipline_advice_id IS NOT NULL AND deleted_date IS NULL;

DO $$
DECLARE
    strategy_mismatch BIGINT;
    advice_mismatch BIGINT;
BEGIN
    SELECT count(*) INTO strategy_mismatch
    FROM fund_strategy strategy
    LEFT JOIN discipline_strategy migrated ON migrated.legacy_strategy_id = strategy.id
    WHERE strategy.fund_id IS NOT NULL AND migrated.id IS NULL;
    SELECT count(*) INTO advice_mismatch
    FROM signal_log advice
    LEFT JOIN discipline_advice migrated ON migrated.legacy_signal_id = advice.id
    WHERE advice.fund_id IS NOT NULL AND migrated.id IS NULL;
    IF strategy_mismatch > 0 OR advice_mismatch > 0 THEN
        RAISE EXCEPTION 'discipline backfill reconciliation mismatch: strategies=%, advice=%',
                strategy_mismatch, advice_mismatch;
    END IF;
END $$;
