-- InvestmentPlan expand migration.
-- Legacy fund_dca_plan and user_config remain readable until scheduler and Web paths have switched.

DO $$
DECLARE
    orphan_plan_count BIGINT;
BEGIN
    SELECT count(*) INTO orphan_plan_count
    FROM fund_dca_plan plan
    LEFT JOIN portfolio_fund portfolio_fund ON portfolio_fund.legacy_fund_id = plan.fund_id
    WHERE portfolio_fund.id IS NULL;
    IF orphan_plan_count > 0 THEN
        RAISE EXCEPTION 'investment plan backfill blocked: plans without portfolio_fund=%', orphan_plan_count;
    END IF;
END $$;

CREATE TABLE investment_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_date TIMESTAMPTZ,
    legacy_dca_plan_id BIGINT UNIQUE,
    portfolio_fund_id BIGINT NOT NULL REFERENCES portfolio_fund (id),
    owner_id BIGINT NOT NULL REFERENCES site_user (id),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    amount NUMERIC(19, 8) NOT NULL,
    frequency VARCHAR(32) NOT NULL,
    day_of_week INTEGER,
    day_of_month INTEGER,
    status VARCHAR(32) NOT NULL
);

CREATE UNIQUE INDEX uq_investment_plan_effective
    ON investment_plan (portfolio_fund_id) WHERE status = 'EFFECTIVE' AND deleted_date IS NULL;
CREATE INDEX idx_investment_plan_owner_status
    ON investment_plan (owner_id, status) WHERE deleted_date IS NULL;

INSERT INTO investment_plan (
    version, created_date, updated_date, deleted_date, legacy_dca_plan_id, portfolio_fund_id, owner_id,
    enabled, amount, frequency, day_of_week, day_of_month, status
)
SELECT COALESCE(plan.version, 0), COALESCE(plan.created_date, now()),
       COALESCE(plan.updated_date, plan.created_date, now()), plan.deleted_date, plan.id,
       portfolio_fund.id, portfolio_fund.owner_id, COALESCE(plan.enabled, TRUE), plan.amount,
       plan.frequency, plan.day_of_week, plan.day_of_month, plan.status
FROM fund_dca_plan plan
JOIN portfolio_fund portfolio_fund ON portfolio_fund.legacy_fund_id = plan.fund_id;

CREATE TABLE investment_plan_budget (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    owner_id BIGINT NOT NULL REFERENCES site_user (id),
    monthly_budget NUMERIC(19, 8),
    CONSTRAINT uq_investment_plan_budget_owner UNIQUE (owner_id),
    CONSTRAINT ck_investment_plan_budget_positive CHECK (monthly_budget IS NULL OR monthly_budget > 0)
);

INSERT INTO investment_plan_budget (owner_id, monthly_budget)
SELECT config.owner_id, config.monthly_dca_budget
FROM user_config config
WHERE config.owner_id IS NOT NULL;

ALTER TABLE fund_transaction ADD COLUMN investment_plan_id BIGINT;
ALTER TABLE fund_transaction ADD CONSTRAINT fk_fund_transaction_investment_plan
    FOREIGN KEY (investment_plan_id) REFERENCES investment_plan (id);
UPDATE fund_transaction transaction_ledger
SET investment_plan_id = plan.id
FROM investment_plan plan
WHERE plan.legacy_dca_plan_id = transaction_ledger.dca_plan_id;
CREATE UNIQUE INDEX uq_fund_transaction_investment_plan_beijing_day
    ON fund_transaction (investment_plan_id, ((trade_date AT TIME ZONE 'Asia/Shanghai')::date))
    WHERE investment_plan_id IS NOT NULL AND trade_date IS NOT NULL AND deleted_date IS NULL;

DO $$
DECLARE
    plan_mismatch BIGINT;
BEGIN
    SELECT count(*) INTO plan_mismatch
    FROM fund_dca_plan plan
    LEFT JOIN investment_plan migrated ON migrated.legacy_dca_plan_id = plan.id
    WHERE migrated.id IS NULL;
    IF plan_mismatch > 0 THEN
        RAISE EXCEPTION 'investment plan backfill reconciliation mismatch=%', plan_mismatch;
    END IF;
END $$;
