-- Final discipline classification is scoped to a user's PortfolioFund.
-- The legacy fund.fund_category stays in place for rollback and comparison.
DO $$
DECLARE
    orphan_count BIGINT;
BEGIN
    SELECT count(*) INTO orphan_count
    FROM fund legacy_fund
    LEFT JOIN portfolio_fund portfolio_fund ON portfolio_fund.legacy_fund_id = legacy_fund.id
    WHERE legacy_fund.fund_category IS NOT NULL AND portfolio_fund.id IS NULL;

    IF orphan_count > 0 THEN
        RAISE EXCEPTION 'discipline classification backfill blocked: legacy funds without portfolio_fund=%', orphan_count;
    END IF;
END $$;

CREATE TABLE discipline_classification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    portfolio_fund_id BIGINT NOT NULL UNIQUE REFERENCES portfolio_fund (id),
    owner_id BIGINT NOT NULL REFERENCES site_user (id),
    category VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'LEGACY_MIGRATION',
    CONSTRAINT ck_discipline_classification_category
        CHECK (category IN ('BROAD_BASE', 'SECTOR', 'ACTIVE', 'MIXED')),
    CONSTRAINT ck_discipline_classification_source
        CHECK (source IN ('LEGACY_MIGRATION', 'DEFAULT_SUGGESTION', 'USER_CONFIRMED', 'USER_CUSTOMIZED'))
);

CREATE INDEX idx_discipline_classification_owner ON discipline_classification (owner_id, portfolio_fund_id);

INSERT INTO discipline_classification (created_date, updated_date, portfolio_fund_id, owner_id, category)
SELECT COALESCE(legacy_fund.created_date, now()), COALESCE(legacy_fund.updated_date, legacy_fund.created_date, now()),
       portfolio_fund.id, portfolio_fund.owner_id, legacy_fund.fund_category
FROM fund legacy_fund
JOIN portfolio_fund portfolio_fund ON portfolio_fund.legacy_fund_id = legacy_fund.id
WHERE legacy_fund.fund_category IS NOT NULL;

DO $$
DECLARE
    mismatch_count BIGINT;
BEGIN
    SELECT count(*) INTO mismatch_count
    FROM fund legacy_fund
    JOIN portfolio_fund portfolio_fund ON portfolio_fund.legacy_fund_id = legacy_fund.id
    LEFT JOIN discipline_classification classification ON classification.portfolio_fund_id = portfolio_fund.id
    WHERE legacy_fund.fund_category IS NOT NULL
      AND (classification.id IS NULL OR classification.category <> legacy_fund.fund_category);

    IF mismatch_count > 0 THEN
        RAISE EXCEPTION 'discipline classification backfill reconciliation mismatch=%', mismatch_count;
    END IF;
END $$;
