-- 智能定投扩展：保留 amount 作为基础金额，新增本地规则结果和指数估值快照。
ALTER TABLE investment_plan ADD COLUMN amount_strategy VARCHAR(32) NOT NULL DEFAULT 'FIXED';
ALTER TABLE investment_plan ADD COLUMN reference_index_code VARCHAR(32);
ALTER TABLE investment_plan ADD COLUMN moving_average_days INTEGER;

ALTER TABLE investment_plan ADD CONSTRAINT ck_investment_plan_amount_strategy
    CHECK (amount_strategy IN ('FIXED', 'LOW_VALUATION', 'MOVING_AVERAGE', 'CHANGE_RATE'));
ALTER TABLE investment_plan ADD CONSTRAINT ck_investment_plan_moving_average_days
    CHECK (moving_average_days IS NULL OR moving_average_days IN (180, 250, 500));

CREATE TABLE index_valuation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    index_code VARCHAR(32) NOT NULL,
    trade_date TIMESTAMPTZ NOT NULL,
    pe_ratio NUMERIC(19, 8) NOT NULL,
    source VARCHAR(64) NOT NULL,
    CONSTRAINT ck_index_valuation_pe_positive CHECK (pe_ratio > 0),
    CONSTRAINT uq_index_valuation_code_date_source UNIQUE (index_code, trade_date, source)
);
CREATE INDEX idx_index_valuation_code_date ON index_valuation (index_code, trade_date DESC);

CREATE TABLE investment_plan_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    investment_plan_id BIGINT NOT NULL REFERENCES investment_plan (id),
    business_date TIMESTAMPTZ NOT NULL,
    amount_strategy VARCHAR(32) NOT NULL,
    rule_version VARCHAR(64) NOT NULL,
    result VARCHAR(16) NOT NULL,
    reason_code VARCHAR(64) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    base_amount NUMERIC(19, 8) NOT NULL,
    actual_amount NUMERIC(19, 8),
    deduction_rate NUMERIC(19, 8),
    data_date TIMESTAMPTZ,
    reference_index_code VARCHAR(32),
    moving_average_days INTEGER,
    primary_metric NUMERIC(19, 8),
    secondary_metric NUMERIC(19, 8),
    CONSTRAINT uq_investment_plan_execution_day UNIQUE (investment_plan_id, business_date),
    CONSTRAINT ck_investment_plan_execution_result CHECK (result IN ('EXECUTED', 'SKIPPED')),
    CONSTRAINT ck_investment_plan_execution_strategy
        CHECK (amount_strategy IN ('FIXED', 'LOW_VALUATION', 'MOVING_AVERAGE', 'CHANGE_RATE'))
);
CREATE INDEX idx_investment_plan_execution_plan_date
    ON investment_plan_execution (investment_plan_id, business_date DESC);
