-- =============================================================================
-- V4: 基金字典表(ADR-0005)
--   东方财富 fundcode_search.js 全量字典(约 2 万条)的本地镜像 + 识别结果缓存。
--   新建基金搜索框查这张表做自动补全,毫秒级响应、不撞外部限流。
--   落库时同步跑 fundSubType + fundCategory + benchmarkIndexCode 识别并缓存,
--   搜索返回的候选自带分类,避免运行时重复识别。
--
--   写入只发生在 FundDictSyncJob 同步任务(读多写少),搜索接口只读。
--   fund_code 全局唯一(部分唯一索引兜底,软删行不占唯一名额)。
-- =============================================================================

CREATE TABLE fund_dict
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               BIGINT,
    created_date          TIMESTAMPTZ,
    updated_date          TIMESTAMPTZ,
    deleted_date          TIMESTAMPTZ,

    fund_code             VARCHAR(16)  NOT NULL,
    fund_name             VARCHAR(255) NOT NULL,
    raw_name              VARCHAR(64),
    fund_sub_type         VARCHAR(32),
    fund_category         VARCHAR(32),
    benchmark_index_code  VARCHAR(64)
);

-- 按代码精确查 + 按名称模糊查的索引
CREATE INDEX idx_fund_dict_code
    ON fund_dict (fund_code) WHERE deleted_date IS NULL;

CREATE INDEX idx_fund_dict_name
    ON fund_dict (fund_name) WHERE deleted_date IS NULL;

-- fund_code 全局唯一(软删行不占唯一名额)
CREATE UNIQUE INDEX uq_fund_dict_code
    ON fund_dict (fund_code) WHERE deleted_date IS NULL;
