CREATE TABLE fund_research (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    fund_code VARCHAR(16) NOT NULL UNIQUE,
    profile_data TEXT,
    profile_source_name VARCHAR(255),
    profile_source_url VARCHAR(1000),
    profile_report_date TIMESTAMPTZ,
    profile_fetched_at TIMESTAMPTZ,
    profile_status VARCHAR(16) CHECK (profile_status IN ('SUCCESS', 'FAILED')),
    scale_data TEXT,
    scale_source_name VARCHAR(255),
    scale_source_url VARCHAR(1000),
    scale_report_date TIMESTAMPTZ,
    scale_fetched_at TIMESTAMPTZ,
    scale_status VARCHAR(16) CHECK (scale_status IN ('SUCCESS', 'FAILED')),
    holdings_data TEXT,
    holdings_source_name VARCHAR(255),
    holdings_source_url VARCHAR(1000),
    holdings_report_date TIMESTAMPTZ,
    holdings_fetched_at TIMESTAMPTZ,
    holdings_status VARCHAR(16) CHECK (holdings_status IN ('SUCCESS', 'FAILED')),
    industry_data TEXT,
    industry_source_name VARCHAR(255),
    industry_source_url VARCHAR(1000),
    industry_report_date TIMESTAMPTZ,
    industry_fetched_at TIMESTAMPTZ,
    industry_status VARCHAR(16) CHECK (industry_status IN ('SUCCESS', 'FAILED')),
    last_attempt_at TIMESTAMPTZ
);

CREATE INDEX idx_fund_research_refresh ON fund_research (last_attempt_at, fund_code);
ALTER TABLE fund_fee
    ADD COLUMN management_fee NUMERIC(19, 8),
    ADD COLUMN custody_fee NUMERIC(19, 8),
    ADD COLUMN purchase_status VARCHAR(16),
    ADD COLUMN purchase_limit NUMERIC(19, 2),
    ADD COLUMN minimum_purchase_amount NUMERIC(19, 2),
    ADD COLUMN channel_reference_label VARCHAR(255),
    ADD COLUMN source_name VARCHAR(255),
    ADD COLUMN source_url VARCHAR(1000),
    ADD COLUMN refresh_status VARCHAR(16) NOT NULL DEFAULT 'SUCCESS';

ALTER TABLE fund_fee
    ADD CONSTRAINT ck_fund_fee_purchase_status
        CHECK (purchase_status IS NULL OR purchase_status IN ('OPEN', 'SUSPENDED', 'LIMITED', 'UNKNOWN')),
    ADD CONSTRAINT ck_fund_fee_refresh_status
        CHECK (refresh_status IN ('SUCCESS', 'FAILED'));
