-- 价格提醒规则:全局规则 portfolio_fund_id 为空,单基金规则必填;单基金规则优先级高于全局规则。
CREATE TABLE alert_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    created_date TIMESTAMPTZ,
    updated_date TIMESTAMPTZ,
    deleted_date TIMESTAMPTZ,
    owner_id BIGINT NOT NULL REFERENCES site_user (id),
    scope VARCHAR(16) NOT NULL,
    portfolio_fund_id BIGINT REFERENCES portfolio_fund (id),
    rule_type VARCHAR(16) NOT NULL,
    threshold NUMERIC(19,8) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_alert_rule_scope_target CHECK (
        (scope = 'GLOBAL' AND portfolio_fund_id IS NULL)
        OR (scope = 'FUND' AND portfolio_fund_id IS NOT NULL)),
    CONSTRAINT ck_alert_rule_threshold CHECK (threshold > 0 AND threshold <= 1)
);

CREATE INDEX idx_alert_rule_owner ON alert_rule (owner_id) WHERE deleted_date IS NULL;
CREATE INDEX idx_alert_rule_enabled ON alert_rule (enabled) WHERE deleted_date IS NULL;

-- 提醒发送记录:仅追加,不物理删除;记录触发条件快照便于历史回看。
CREATE TABLE alert_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    created_date TIMESTAMPTZ,
    updated_date TIMESTAMPTZ,
    deleted_date TIMESTAMPTZ,
    owner_id BIGINT NOT NULL REFERENCES site_user (id),
    alert_rule_id BIGINT NOT NULL REFERENCES alert_rule (id),
    trigger_type VARCHAR(16) NOT NULL,
    threshold NUMERIC(19,8) NOT NULL,
    trading_date TIMESTAMPTZ NOT NULL,
    status VARCHAR(16) NOT NULL,
    recipient_email VARCHAR(255),
    fund_count INTEGER NOT NULL,
    trigger_summary VARCHAR(512) NOT NULL,
    failure_reason VARCHAR(255),
    sent_at TIMESTAMPTZ
);

-- 幂等键:同一规则同一交易日最多只允许一条成功记录;失败行不占用额度,可重复重试。
CREATE UNIQUE INDEX uq_alert_notification_rule_day_sent
    ON alert_notification (alert_rule_id, ((trading_date AT TIME ZONE 'UTC')::date))
    WHERE deleted_date IS NULL AND status = 'SENT';

CREATE INDEX idx_alert_notification_owner_date
    ON alert_notification (owner_id, trading_date DESC) WHERE deleted_date IS NULL;
