-- 提醒规则分类:通用条件规则(CONDITION)与两条建议型规则(LOGIC_BROKEN 逻辑破坏止损 / TRAILING_STOP 回撤止盈)。
-- 建议型规则的参数单独存 JSON(仅回撤止盈需要六个参数),通用规则为空。
-- 回撤止盈的判定由「参数 + 状态机」决定,不写条件数组,故 conditions 允许为空。
ALTER TABLE alert_rule ADD COLUMN kind VARCHAR(24);
UPDATE alert_rule SET kind = 'CONDITION' WHERE kind IS NULL;
ALTER TABLE alert_rule ALTER COLUMN kind SET NOT NULL;
ALTER TABLE alert_rule ADD COLUMN parameters TEXT;
ALTER TABLE alert_rule ALTER COLUMN conditions DROP NOT NULL;

-- 建议型规则的运行期状态:阶段、周期起始、周期峰值、冷静期起始。
-- 回撤止盈用它实现「同一信号不逐日重复发送」;逻辑破坏止损复用它做「连续命中期间只提醒一次」的抑制(不写峰值)。
CREATE TABLE alert_suggestion_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    created_date TIMESTAMPTZ,
    updated_date TIMESTAMPTZ,
    deleted_date TIMESTAMPTZ,
    alert_rule_id BIGINT NOT NULL REFERENCES alert_rule (id),
    owner_id BIGINT NOT NULL REFERENCES site_user (id),
    portfolio_fund_id BIGINT NOT NULL REFERENCES portfolio_fund (id),
    phase VARCHAR(16) NOT NULL,
    cycle_started_at TIMESTAMPTZ,
    cycle_peak_nav NUMERIC(19,8),
    cooldown_started_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_alert_suggestion_state_rule_fund
    ON alert_suggestion_state (alert_rule_id, portfolio_fund_id) WHERE deleted_date IS NULL;